# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  push:
    branches:
      - release
    tags:
      - "v*"
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # APP name
  APP_NAME: vvibe


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.2
          
      - name: Install Dependences
        run: |
          flutter doctor --verbose
          flutter config --enable-windows-desktop
          flutter pub get
          # nightly will crash
          curl https://master.dl.sourceforge.net/project/mdk-sdk/mdk-sdk-windows-desktop-vs2022-x64.7z?viasf=1 -o mdk-sdk-windows-desktop-vs2022-x64.7z
          mv mdk-sdk-windows-desktop-vs2022-x64.7z windows/flutter/ephemeral/.plugin_symlinks/fvp/windows
          
      - name: Build Windows
        run: |
          flutter build windows --verbose --release
          cp -r build/windows/x64/runner/Release .
          7z a vvibe-${{github.ref_name}}-windows-x64.zip  Release

      - name: Release  Windows Artifact 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          draft: true
          prerelease: true
          token: ${{ secrets.GH_TOKEN }}
          files: |
            vvibe-${{github.ref_name}}-windows-x64.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: vvibe-${{github.ref_name}}-windows-x64.zip
          path: vvibe-${{github.ref_name}}-windows-x64.zip
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.27.2

    - name: Install Dependences
      run: |
       sudo apt-get update -y
       sudo apt-get install -y unzip xz-utils zip libglu1-mesa cmake clang ninja-build pkg-config libgtk-3-dev libpulse-dev liblzma-dev  libstdc++-10-dev  libasound2-dev

    - name: Build Linux
      run: |
          flutter config --enable-linux-desktop
          flutter doctor --verbose
          flutter pub get
          # nightly will crash
          curl https://master.dl.sourceforge.net/project/mdk-sdk/mdk-sdk-linux-x64.tar.xz?viasf=1 -o mdk-sdk-linux-x64.tar.xz
          mv mdk-sdk-linux-x64.tar.xz linux/flutter/ephemeral/.plugin_symlinks/fvp/linux
          flutter build linux --verbose --release
          cp -r build/linux/x64/release/bundle .
          tar Jcvf vvibe-${{github.ref_name}}-linux-x64.tar.xz bundle

    - name: Release Linux Artifact 
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{github.ref_name}}
        draft: true
        prerelease: true
        token: ${{ secrets.GH_TOKEN }}
        files: |
          vvibe-${{github.ref_name}}-linux-x64.tar.xz

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: vvibe-${{github.ref_name}}-linux-x64.tar.xz
        path: vvibe-${{github.ref_name}}-linux-x64.tar.xz

