# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # APP name
  APP_NAME: vvibe


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Windows:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.1
          cache: true

      - name: Build
        run: |
          flutter doctor --verbose
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --verbose
          mv build/windows/x64/runner/Release .
          cmake -E tar cvf vvibe-${{github.ref_name}}-windows-x64.7z --format=7zip Release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          draft: true+
          prerelease: true
          token: ${{ secrets.GH_TOKEN }}
          files: |
            vvibe-${{github.ref_name}}-windows-x64.7z

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: vvibe-${{github.ref_name}}-windows-x64.7z
          path: vvibe-${{github.ref_name}}-windows-x64.7z
  Linux:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        flutter-version: 3.27.1
        cache: true
    - run: |
       sudo apt-get update -y
       sudo apt-get install -y unzip xz-utils zip libglu1-mesa cmake clang ninja-build pkg-config libgtk-3-dev libpulse-dev liblzma-dev  libstdc++-12-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter doctor --verbose
    - run: flutter pub get
    - run: flutter build linux --verbose --release
    #- run: mv build/linux/x64/release/bundle .
    - run:  cmake -E tar Jcvf vvibe-${{github.ref_name}}-linux-x64.tar.xz build/linux/x64/release/bundle

    - name: Archive Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{github.ref_name}}
        draft: true
        prerelease: true
        token: ${{ secrets.GH_TOKEN }}
        files: |
          vvibe-${{github.ref_name}}-linux-x64.tar.xz

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: vvibe-${{github.ref_name}}-linux-x64.tar.xz
        path: vvibe-${{github.ref_name}}-linux*.tar.xz

