name: dev
on:
  push:
    branches: 
     - dffffffjjdj
env:
  # APP name
  APP_NAME: vvibe
  FVP_DEPS_LATEST: 1
  FLUTTER_VERSION: 3.27.3
jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "flutter version: ${FLUTTER_VERSION}"
  
