# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # APP name
  APP_NAME: vvibe

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      ffmpeg_url: https://github.com/GyanD/codexffmpeg/releases/download/4.4.1/ffmpeg-4.4.1-full_build-shared.7z
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
      - name: download ffmpeg builds 
        run: |
          curl -L ${{env.ffmpeg_url}} -o ffmpeg-release-full.7z
          mkdir ffmpeg-release-full || true
          7z e ffmpeg-release-full.7z -offmpeg-release-full "**/bin/*.dll"
          
      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
          del rustup-init.exe
        shell: powershell

      - name: copy ffmpeg lib to cargo
        run: |
          ls
          mv ffmpeg-release-full/*.dll C:\Users\runneradmin\.cargo\bin
          cd C:\Users\runneradmin\.cargo\bin
          ls
          
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: vvibe-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          draft: true
          prerelease: true
          token: ${{ secrets.GH_TOKEN }}
          files: |
            build/windows/runner/Release/vvibe-${{github.ref_name}}-windows.zip

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: artifact-windows
          path: build/windows/runner/Release/vvibe-${{github.ref_name}}-windows.zip
